# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "CI" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Update
      run: |
        sudo apt-get update
        sudo python -m pip install --upgrade pip
        sudo pip install flake8
        
    - name: env python
      run: |
        sudo apt-get install python3-venv
        python3 -m venv env
        
        
    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      
    - name: sphinx
      run: |
        pip install sphinx
        cd docs
        make html
      
    - name: Install dependencies
      run: |
        sudo pip3 install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 --extend-ignore=E302,E101,E131,W191,W293,W292,W291 --count --select=E9,F63,F7,F82 --exclude=*.pyc,*migrations* --show-source --statistics
        flake8 --extend-ignore=E302,E101,E131,W191,W293,W292,W291 --count --max-complexity=10 --max-line-length=226 --exclude=*.pyc,*migrations* --statistics
      
    - name: Test with pytest
      run: |
        sudo pip install pytest
        pytest --cov