# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "CI" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Update
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install flake8 pytest
        
    - name: env python
      run: |
        sudo apt-get install python3-venv
        python3 -m venv env
        
        
    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      
    - name: sphinx
      run: |
        pip install sphinx
        cd docs
        make html
      
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
      
    - name: Test with pytest
      run: |
        pytest